# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-01 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimental_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product_image')),
                ('description', models.TextField()),
            ],
        ),
    ]
